### PR TITLE
Arrow Predictions

### LINKED ISSUE #63: Arrow Collision
Multiple exploding arrows shot from [(targetting spells) + Exploding Arrow] will repeatedly collide with the first enemy, even after that enemy has been killed. This leads to incorrect predictions.

### PR DESCRIPTION
**Pull request by SoulMuncher**
Closes #63

WIP - Visual discrepancies in multiplayer. #166 is very apparent here.

See latest comments

### CODE REVIEW

**Comment by SoulMuncher** [comment]
As of the last commit [9d9f3f0]:

Arrow collisions are only calculated in predictions, which means predictions should be 100% accurate. This also means that arrows will keep the same visuals and coolness they had before and can still run synchronously without interfering with one another or other spell effects. Lastly, all arrows now use the basic arrowEffect function, which centralizes the code and makes it much more maintainable. There are three problems left to address:

- Shatter Arrow collides with initial target - Game loop only, probably a simple fix with the onCollide event promise.
- Stacked Exploding Arrow repeatedly hits target out of range - Prediction only, probably a simple fix with the onCollide event promise.
- All arrows look like they pierce in multiplayer. This is because predictedArrowCollisions[][] is not synced over the network. As far as I can tell, this is purely visual. I will do more testing once shatter/explosive arrow are fixed.

**Comment by SoulMuncher** [comment]
Great idea @jdoleary 

One issue I'm seeing is that this inner prediction messes with the actual prediction. It's not entirely local. I'm not sure if it could be made local either since we need to run onCollide events and as an extention, things like forcePush.

**Comment by jdoleary** [comment]
Can you reset the predictions with syncPredictionEntities between use?

**Comment by SoulMuncher** [comment]
> @jdoleary Can you reset the predictions with syncPredictionEntities between use?

Sort've. It clears other spell predictions too, so it looks a little weird. If you were to just use slashes it would keep the prediction/death icon until the spell is done.

https://github.com/jdoleary/Spellmasons/assets/68413161/0c4caa71-44df-43ed-9c4b-0b7c1950e536

**Comment by jdoleary** [comment]
Replaced by #303

**Pull request closed without merging**
