### PR TITLE
Class-Specific Spells

### PR DESCRIPTION
**Pull request by Couls**
Make mage types feel more unique by offering spells that are only offered if you belong to the certain magetype, currently a draft as its not complete but I wanted to put up a PR to gauge approval and see if there are any thoughts about the idea, inside the PR is a design document with a few ideas floating around for each class type, implemented so far is the Regenerate spell for clerics that allows you to apply a regenerating effect on a target to heal 30 hit points, stackable for extending the duration, a powerful healing option that could synergize well with a necromancer or summons that helps keep them topped up, but useless if you're killed

If the idea is well-received, the goal would be to get in at least one class-specific spell with this PR

# Implemented

# Cleric
## Regenerate
Heal 30 hit points each round, stackable to increase duration
Implementation: Use an effect for regenerate
image
Reused heal art, would probably want to get a different icon before this is implemented

# Ideas

# Necromancer

## Dark bolt
Send a bolt of necromantic damage to an enemy, heal 50% of that damage, damage similar to an unupgraded arrow, helps with the health costs of raising dead
Implementation: Use a spell card is fine

## Hex
Pairs well with decoy, enemy takes damage equal to the damage they deal for rounds equal to the stacks of the spell

# Far-Gazer
## Sniping Stance
Adds % damage to first hit of the next attack equal to stamina expended / 10, encourages you to stay still, removes cap from Long Arrow/Shot/Whatever that spell is called
Implementation: Probably another effect, expires after a turn, listens for damage somehow. May be kinda hard to implement

# Archer
## Pinning Shots
Any enemies hit by attacks with this modifier have their stamina reduced to 0 for a round

# Witch
## Voodoo Doll
Deal half the damage dealt to this enemy once the effect expires, stacks increase how many turns the cumulative damage is stored for

## Glacial Freeze [Freeze Upgrade]
Deals damage while frozen equal to (number of curses * 10/max mana). 
capped to max mana, increases vulnerability by 50%

## Complex Bloat [Bloat Upgrade]
Can store a single spell in Complex Bloat by casting it before Bloat [Mainly for vortex], the spell is ignored when initially cast
Implementation: May be really hard to implement, if so maybe cut it for now

# Gambler
## Roll The Dice
Randomly modify the damage of the next spell combo by anywhere between 50% and 200%

## Lucky Shot
Ranged attack that deals variable damage, has a chance to ricochet to a nearby enemy

## Shuffle The Cards
Randomize the targets health, mana and stamina (max health may turn into max stamina, max stamina may turn to max health etc)
Implementation: Store current values and make sure they remain consistent after shuffling, you don't want to instakill someone because they had 0 stamina and their health turned to stamina

### CODE REVIEW

**Comment by jdoleary** [comment]
Hey Couls!
I agree that the classes are kind of missing a unique identity.
Long term, I'm planning to replace classes with runes (Slay the Spire style).  As it is now, classes are kind of isolated.  There's no combination possibilities and many classes only have 1 or 2 interesting things about them.  There's been a lot of cool ideas from the community about possible runes, and so I will eventually just convert the aspects of the classes into runes.

As for your spell ideas, a lot of them would fit great!  I especially love "Pinning Shot".  Note that Regenerate already exists in the Wode's Grimoire mod (similar effect too).
Ricocheting arrows, voodoo doll, sniping stance, dark bolt are all awesome spell ideas!

**Comment by Couls** [comment]
There are a few proposals that can be made to fit those long term goals, we could have two game modes, one for a rogue like style play with runes and one like the current with classes

Alternatively classes could be given specific types of perks or perk trees as well potentially ones that overlap, also thanks for the heads up about the regenerate spell I’ll see if I can get in touch with the modder to include their implementation with credit

Mainly while I like potent and powerful perks and abilities classes have the potential to give you a unique style off the bat unbounded(but potentially enhanced) by RNG so I would like to see some kind of way to make sure we don’t have a situation where you’re kind of just hoping for RNG to bless you with perks that synergize well and instead design perks and options that already synergize well with their initial choices off the bat

**Comment by jdoleary** [comment]
>  just hoping for RNG to bless you with perks that synergize well and instead design perks and options that already synergize well with their initial choices off the bat

Yes, this is actually an element of the current design that I want to keep.  It's one of the things players like about classes is that it's not random.  So I'll probaby have core runes that you get to choose and then the rest are random or something.

I'm not planning for multiple game modes or perk trees.   I've got my hands full with other priorities and I really don't have the time to maintain code two separate modes.  I just reworked the roadmap in the Discord: https://discord.com/channels/1032294536640200766/1073660362592895018
Check it out to see what I'm planning.

In any case, lots of those spells would be cool even unattached to classes.  If you're still interested in working on them, feel free to submit them as a PR in the mods repo: https://github.com/jdoleary/spellmasons-mods
So that players can elect to use them or not.

**Comment by Couls** [comment]
That’s very fair, thanks for the responses and having this discussion with me having class-style rune load outs to ensure that you get a workable build is enough for me, I’ll hold off this PR for now and see if I can rework these ideas and contribute some runes when it comes time for that system to be included instead

**Comment by jdoleary** [comment]
Of course! Thank you for your contributions and interest in being a part of Spellmasons!

**Pull request closed without merging**
