### PR TITLE
Meteor

### LINKED ISSUE #473: New Spell: Meteor
Meteor falls on top of enemies doing splash damage around them

### PR DESCRIPTION
**Pull request by SoulMuncher**
Closes #473 

Summons a meteor from the sky which deals massive damage in an area on impact

## TODO
- VFX Improvements
- i18 description

### CODE REVIEW

**Comment by jdoleary** [comment]
We should use particles to animate a meteor coming down from the sky, I can show you how to use the particle editor (https://pixijs.io/pixi-particles-editor/#) and how you import it's settings into the game
(Note the size of the particles shows as larger(smaller?) in the editor than they do in game when you export and include the particle settings.

**Comment by jdoleary** [comment]
In order to animate the particles trailing off the meteor, you should be able to reuse projectile functions (in arrow) but without the collision) and attach the particle emitter to the projectile (like how they're attached to the deathmason).
I'd say have the meteor come in from an angle above (like a 30 degree angle down)

**Comment by jdoleary** [comment]
I LOVE it!  Very fun to call down meteors.
Some notes:
- The particles should be "left behind" as the meteor travels through space - not streaming out of it.  See how this is done with the deathmason particles (if you push the deathmason, you'll see it).
- Have the meteor start up higher and move faster
- I want multiple meteors from a single case to have a delay (like multiple arrows) rather than coming down all at the same time)
- use public/images/empty.png for the image

**Comment by SoulMuncher** [comment]
@jdoleary 

> * I want multiple meteors from a single case to have a delay (like multiple arrows) rather than coming down all at the same time)

This makes the spell very unpredictable due to the AoE knockback, and it'll make the in-game predictions inaccurate unless we do a lot of special work with it like we did with arrows (even then I'm not 100% sure it will work/feel good). Lots of things to consider here with awaiting, overlapping force pushes, and hitting/not hitting initially targeted/not targeted things.

> * use public/images/empty.png for the image

"public/images/empty.png" doesn't work with Image.create since it starts in the other image/ folder. I didn't see images/empty used anywhere else in the codebase so I'm not really sure how to do that

**Comment by jdoleary** [comment]
Right, I see what you're saying.  Okay for now, ignore what I said about empty.png and separating the timings of the meteors.
A few notes.  Because they start at 0,0 there's some particles that always end up at 0,0.
I'd like the meteors to start up much higher.  They appear and come in so fast that you can't really enjoy the anticipation of the collision and it looks weird if you're zoomed way out.

**Comment by SoulMuncher** [comment]
> some particles that always end up at 0,0

Having some trouble fixing this one. It's happening due to Pixi's innate emitter-position-interpolation. For some reason the particle emitters always start interpolating from 0,0, which is why they're appearing there even though the meteors are initialized elsewhere, and emitters attached directly to them. It happens with the Deathmason as well: when he spawns/teleports you'll see interpolated particles between 0,0 and his spawn, or between point A and B of the TP.

**There is a function on the emitter called resetPositionTracking() which is supposed to fix this**, but I haven't had much luck with it. This was the fix I just attempted in the meteor script:

```
if (wrapped) {
      const particleFollower = {
        displayObject: wrapped.container,
        emitter: wrapped.emitter,
        target,
      }
      particleFollower.emitter.resetPositionTracking();
      underworld.particleFollowers.push(particleFollower);
    } else {
      console.warn('Failed to create meteor particle emitter');
    }
```

Will keep looking for a solution.

Meteors now spawn 5x higher and with almost 3x the total travel time (Making them move faster but also giving more anticipation. Looks much better when zoomed out!)

**Comment by SoulMuncher** [comment]
Also, would you have any idea how to keep the emitter particles around after the meteor has landed? I think that would do a TON for the vfx. Currently they're being destroyed along with the force move projectile, since the emitter no longer has a target, but the already emit particles should persist.

I tried detaching the particles and setting a new target/disabling emission via an OnProjectileCollision event with the meteors but I coudn't quite figure it out

**Comment by jdoleary** [comment]
I'm going to make a separate issue for these two remaining so we can move on and I'll investigate those issues further later.
For now let's move on so we don't get stuck on this.

https://github.com/jdoleary/Spellmasons/issues/523

With that in mind, do you feel that meteor is ready to merge.  I'm pretty happy with it

**Comment by SoulMuncher** [comment]
Yes, other than those 2 particle behaviors I think it's ready!

**Review by jdoleary — APPROVED** [review]
I'm very happy with this! Great work!

**Pull request merged**
